
const Data = [  
    {
        imgsrc: "https://www.mecgale.com/wp-content/uploads/2017/08/dummy-profile.png",
        name: "Olive Yew",
        age: "35",
        addres:"514 Lawrence St.High Point",
        city:"New York",
        pin:"99501",
        state:"Alaska",
        mobile:"+1-202-555-0117",
        email:"jmorris@att.net",
        school:"Shining Stars",
        edu:"Architecture",
        livesin:"Banff",
        contactus: "https://www.washingtonpost.com/graphics/2019/entertainment/oscar-nominees-movie-poster-design/img/black-panther-web.jpg",
    },
    {
        imgsrc: "https://homeworkforhire.com/wp-content/uploads/2017/10/user9.jpg",
        name: "Aida Bugg",
        age: "30",
        addres:"9206 Greenview Court Evanston",
        city:"Los Angeles",
        pin:"90001",
        state:"California",
        mobile:"+1-202-555-0178",
        email:"balchen@sbcglobal.net",
        school:"Morning Roots School",
        edu:"Arts",
        livesin:"Nelson",
        contactus: "https://www.washingtonpost.com/graphics/2019/entertainment/oscar-nominees-movie-poster-design/img/black-panther-web.jpg",
    },
    {
        imgsrc: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTpxMXSs6SK6Lo0AaIR46KEdM9zeGPPAbds-dqHe_q8oAzO0MRHB9FFNzpq3Y8-vhDtEIA&usqp=CAU",
        name: "Maureen Biologist",
        age: "33",
        addres:"4 Alton St.Chandler",
        city:"Chicago",
        pin:"32003",
        state:"Florida",
        mobile:"+1-202-555-0171",
        email:"jshirley@yahoo.com",
        school:"Global Sparks Academy",
        edu:"Business Administration",
        livesin:"New Westminster",
        contactus: "https://www.washingtonpost.com/graphics/2019/entertainment/oscar-nominees-movie-poster-design/img/black-panther-web.jpg",
    },
    {
        imgsrc: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTYEM5UrdhYGpJa238spzBqd8aQYp8-FX4iSkg8sx_FNAXwRSBVAf0aaLA316-fxbZrK5M&usqp=CAU",
        name: "Teri Dactyl",
        age: "40",
        addres:"574 Brewery St.Lynnwood",
        city:"Houston",
        pin:"30002",
        state:"	Georgia",
        mobile:"+1-202-555-0147",
        email:"rgarton@hotmail.com",
        school:"Star Bright Academy",
        edu:"Business Administration",
        livesin:"White Rock",
        contactus: "https://www.washingtonpost.com/graphics/2019/entertainment/oscar-nominees-movie-poster-design/img/black-panther-web.jpg",
    },
    {
        imgsrc: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTYkw17nWOgWeZJXbWT92rLllmEgNouJRkRhGboMERB0NZemV11z9wEQsaraEX3qaCLT1k&usqp=CAU",
        name: "Peg Legge",
        age: "26",
        addres:"8136 South School Dr.Copperas Cove",
        city:"Phoenix",
        pin:"20588",
        state:"Maryland",
        mobile:"+1-202-555-0160",
        email:"flaviog@sbcglobal.net",
        school:"Sky High School",
        edu:"Fine Arts",
        livesin:"Churchill",
        contactus: "https://www.washingtonpost.com/graphics/2019/entertainment/oscar-nominees-movie-poster-design/img/black-panther-web.jpg",
    },
    {
        imgsrc: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTCuB-G-QAbWR3dI6hi_FfJyAPTKhq6VTJZBm8LMhgJZ_HgX7lEoKgfDedpF6vWRnyGxbQ&usqp=CAU",
        name: "Allie Grater",
        age: "28",
        addres:"7622 Greenview St.Jenison",
        city:"Philadelphia",
        pin:"88901",
        state:"Nevada",
        mobile:"+1-202-555-0133",
        email:"heidrich@yahoo.com",
        school:"New Dawn International",
        edu:"Informational Technology",
        livesin:"Saint Boniface",
        contactus: "https://www.washingtonpost.com/graphics/2019/entertainment/oscar-nominees-movie-poster-design/img/black-panther-web.jpg",
    },
    {
        imgsrc: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRxLDEajEW8QIw_X_Zt5S-1rxj0-lhuljenolf6zjfThRco-WTZIlp_QU-BIFFBhjhp9uM&usqp=CAU",
        name: "Liz Erd",
        age: "35",
        addres:"839 N. Mountainview Ave.Rosedale",
        city:"San Antonio",
        pin:"07001",
        state:"New Jersey",
        mobile:"+1-202-555-0117",
        email:"hoyer@gmail.com",
        school:"City Connection School",
        edu:"Law",
        livesin:"Dalhousie",
        contactus: "https://www.washingtonpost.com/graphics/2019/entertainment/oscar-nominees-movie-poster-design/img/black-panther-web.jpg",
    },
    {
        imgsrc: "https://media.istockphoto.com/photos/headshot-portrait-of-smiling-ethnic-businessman-in-office-picture-id1300512215?k=20&m=1300512215&s=170667a&w=0&h=8haDTC2HXTF6Qb0TkjDy3FauBCd9PCchl6KKX2cUpqg=",
        name: "A. Mused",
        age: "24",
        addres:"73 Blackburn St.Matthews",
        city:"Dallas",
        pin:"00501",
        state:"New York",
        mobile:"+1-202-555-0178",
        email:"lbaxter@verizon.net",
        school:"Oak Tree Academy",
        edu:"Management Studies",
        livesin:"Argentia",
        contactus: "https://www.washingtonpost.com/graphics/2019/entertainment/oscar-nominees-movie-poster-design/img/black-panther-web.jpg",
    },
    {
        imgsrc: "https://media.istockphoto.com/photos/portrait-of-a-confident-mature-businessman-working-in-a-modern-office-picture-id1314997483?k=20&m=1314997483&s=170667a&w=0&h=jxySTisO3-ZWIig-pRW3qzxbHxHMG_OTYl4gTOp_yR8=",
        name: "Ray Sin",
        age: "45",
        addres:"70 Sycamore Ave.Somerset",
        city:"San Jose",
        pin:"73301",
        state:"Texas",
        mobile:"+1-202-555-0171",
        email:"mugwump@live.com",
        school:"The Rising Sun School",
        edu:"Medicine, Bachelors of Surgery",
        livesin:"Labrador City",
        contactus: "https://www.washingtonpost.com/graphics/2019/entertainment/oscar-nominees-movie-poster-design/img/black-panther-web.jpg",
    },
    {
        imgsrc: "https://media-exp1.licdn.com/dms/image/C5103AQEbremhAwrmvg/profile-displayphoto-shrink_400_400/0/1550476192456?e=1672272000&v=beta&t=E3MYzwQ0k36ulVXhKe5ubNinQEe_YdByOofpGZN3M1w",
        name: "Paige Turner",
        age: "38",
        addres:"273 Brook Lane Mays Landing",
        city:"Austin",
        pin:"98001",
        state:"Washington",
        mobile:"+1-202-555-0147",
        email:"trygstad@icloud.com",
        school:"Bright Future School",
        edu:"Science",
        livesin:"St. John’s",
        contactus: "https://www.washingtonpost.com/graphics/2019/entertainment/oscar-nominees-movie-poster-design/img/black-panther-web.jpg",
    },
    {
        imgsrc: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT67PXg-Nzu8La_RtACW1SA-AHLXYBlS9aZMV4nvKsgxkOr-zKdPF2Z-pUa8Gvc1c0kvZE&usqp=CAU",
        name: "Anne Teak",
        age: "32",
        addres:"54 Oxford Ave.Soddy Daisy",
        city:"Jacksonville",
        pin:"35004",
        state:"Alabama",
        mobile:"+1-202-555-0160",
        email:"attwood@me.com",
        school:"Wise Ideas University",
        edu:"Architecture",
        livesin:"Tokyo",
        contactus: "https://www.washingtonpost.com/graphics/2019/entertainment/oscar-nominees-movie-poster-design/img/black-panther-web.jpg",
    },
    {
        imgsrc: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTG5h25nUC2CH2RRC_5Rm29yFLEKzjA9hoeMdwylyHkwEqeeX6fl39TPrwV_j4SxiziNOo&usqp=CAU",
        name: "Harriet Upp",
        age: "35",
        addres:"613 Tallwood Street Mentor",
        city:"Fort Worth",
        pin:"99501",
        state:"Alaska",
        mobile:"+1-202-555-0133",
        email:"uncled@gmail.com",
        school:"Scholars Academy",
        edu:"Arts",
        livesin:"Belleville",
        contactus: "https://www.washingtonpost.com/graphics/2019/entertainment/oscar-nominees-movie-poster-design/img/black-panther-web.jpg",
    },
    
   
];

export default Data;